// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Web;
using System.Web.UI;

namespace Molecule.WebSite.Admin
{
	
	
	public partial class CreateUser
	{
		protected System.Web.UI.WebControls.CreateUserWizard CreateUserWizard1;

		protected System.Web.UI.HtmlControls.HtmlForm form1;

		protected System.Web.UI.WebControls.Button StepPreviousButton;

		protected System.Web.UI.WebControls.Button StepNextButton;

	}
}
