#! /bin/sh
### BEGIN INIT INFO
# Provides:          mono-xsp2
# Required-Start:    
# Required-Stop: 
# Should-Start:      
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mono XSP2
# Description:       Debian init script for Mono XSP2.
### END INIT INFO
#
# Written by Pablo Fischer <pablo@pablo.com.mx>
#            Dylan R. E. Moonfire <debian@mfgames.com>
# Modified for Debian GNU/Linux
#
# Version:	@(#)mono-xsp2 pablo@pablo.com.mx
#

# Variables
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/mod-mono-server2
DAEMONUNIXSOCKET=/tmp/mod_mono_server_molecule-blandine
NAME=molecule-timaniac
DESC="Molecule XSP 2 WebServer"
USER=blandine
GROUP=blandine
MOLECULEDIR=/home/blandine/www/molecule-website

# Use LSB
. /lib/lsb/init-functions

# If we don't have the basics, don't bother
test -x $DAEMON || exit 0
                
case "$1" in
    start)

	    echo "Starting $DESC" "$NAME"
	    start-stop-daemon --start --background --make-pidfile \
		--pidfile /var/run/$NAME.pid \
		--user $USER --group $GROUP --chuid $USER \
		--exec $DAEMON -- \
		--filename $DAEMONUNIXSOCKET --root \
		$MOLECULEDIR --nonstop
	    sleep 2
            chmod 777 $DAEMONUNIXSOCKET
	    
	    log_end_msg $?

	;;
    stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
        for i in $(ps aux | grep -v grep | grep 'mono-server2.exe' | cut -c 10-15)
        do
                kill $i > /dev/null 2>&1
        done
	log_end_msg $?
	;;
    restart|force-reload)
	$0 stop
	$0 start
	;;
    *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
