// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Web;
using System.Web.UI;
using Brettle.Web.NeatUpload;

namespace Upload
{
	
	
	public partial class Default
	{
		protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::Brettle.Web.NeatUpload.MultiFile  multiUploadFile;
		protected global::Brettle.Web.NeatUpload.ProgressBar uploadProgressBar;
		protected global::System.Web.UI.WebControls.Button submitButton;
	}
}
